#! /bin/sh

rm -rf 'sb-server-tests/derby.log'
rm -rf 'sb-server-tests/pstack.application::org_eclipse_jdt_internal_junit_runner_RemoteTestRunner0.55747'
rm -rf 'sb-server/nested.resources.nested-resource-path-resolver-test.txt'
rm -rf 'sb-server/resource-path-resolver-test.txt'

rm -rf 'ldm-client/${env.TIBCO_EP_HOME}'
rm -rf 'ldm-compiler/${env.TIBCO_EP_HOME}'
rm -rf 'ldm-service-layer/${env.TIBCO_EP_HOME}'
rm -rf 'sb-administration/adapter/${env.TIBCO_EP_HOME}'
rm -rf 'sb-administration/clientconnection/${env.TIBCO_EP_HOME}'
rm -rf 'sb-administration/operator/${env.TIBCO_EP_HOME}'
rm -rf 'sb-administration/playback/${env.TIBCO_EP_HOME}'
rm -rf 'sb-administration/record/${env.TIBCO_EP_HOME}'
rm -rf 'sb-client-core/${env.TIBCO_EP_HOME}'
rm -rf 'sb-dt-common/${env.TIBCO_EP_HOME}'
rm -rf 'sb-dt-manager/${env.TIBCO_EP_HOME}'
rm -rf 'sb-dtm/container/${env.TIBCO_EP_HOME}'
rm -rf 'sb-dtm/integration-test/application/.gitignore'
rm -rf 'sb-dtm/integration-test/eventflow-fragment/bin'
rm -rf 'sb-server/${env.TIBCO_EP_HOME}'
